# This is a demo docker-compose file.
# Usage: docker-compose -f docker-compose-demo.yml up [-d]

version: '3.4'

services:
  reaction:
    #image: reactioncommerce/reaction:latest
    image: alfred321/korau-shop:latest
    env_file:
      - .env.dev
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      ROOT_URL: "http://localhost:3000"
      MONGO_URL: "mongodb://mongo:27017/reaction"

  mongo:
    image: mongo:3.6.3
    command: mongod --storageEngine=wiredTiger
    ports:
      - "27017:27017"
